Fix #388
akaAgar/briefing-room-for-dcs pull request #389
Opened 2022-02-27 23:55 UTC by NovaLogicDev

Attempt to address #388

2022-02-28 19:13 UTC, john681611 requested changes
Thanks for the contribution its always appreciated.
Forgive me if this seems a bit savage of a review (I've not had a chance to review propper code in a while so I've gone for it)

Generally, there are some easy readability improvements and I'm generally trying to avoid query like calls in preference for LINQ ones as they flow way better and have half the code IMO. Otherwise like the idea.

Something we will have to do (and I'm hoping you will help out) is creating a bunch more static layouts in order to have sufficient variety that this change won't cause the same layout to be selected each time

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +            throw new Exception("Requested Target Count greater than Maximum Configured Target Count"); //TODO: Unhandled
[suggestion] if valid unit count is 0 then throw error
[issue] Use `BriefingRoomException` its handled

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +        }
[issue] Ref LINQ query suggestion above this can now just be a bool response

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            var minUnitCount = targetDB.UnitCount[(int)objectiveTemplate.TargetCount].Min;
[nitpick] No need for this as `targetDB.UnitCount[(int)objectiveTemplate.TargetCount]` is an object where you can pull min & max cleaner.

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            // Spawn target on airbase
[nitpick] no need for comments here

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            // Set if Objective has Embedded Air Defense
[nitpick] no need for comments here

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            // Determine if Transport Task, if so do things
[nitpick] no need for comments here

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +                objectiveTargetUnitFamily, unitCount, minUnitCount, maxUnitCount,
[issue] ref using single parameter over the two

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            int minUnitCount, int maxUnitCount,
[issue] ref using single parameter over the two

2022-02-28 19:13 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +                objectiveTargetUnitFamily, unitCount, minUnitCount, maxUnitCount,
[issue] ref using single parameter over the two

2022-02-28 19:43 UTC, NovaLogicDev commented
> Something we will have to do (and I'm hoping you will help out) is creating a bunch more static layouts in order to have sufficient variety that this change won't cause the same layout to be selected each time

Is there any trick to creating these? I'm pretty good at programming, horrible at the Mission Editor.

2022-02-28 22:08 UTC, john681611 commented
This file if you can get lua going.
https://github.com/akaAgar/briefing-room-for-dcs/blob/main/dataExtractors/UnitTemplateExtractor.lua

2022-03-01 18:54 UTC, john681611 requested changes
Few minor things but much better.

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +            var validUnits = SelectValidUnits(families, decade, unitMods); //NOTE: I moved this up here so I can do more work with the switch statement
[nitpick] comment not needed here as self explanatory

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                    validUnits = countMinMax.HasValue ? LimitValidUnitsByRequestedUnitCount(countMinMax.Value, validUnits): validUnits;
[praise] much cleaner!

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +            BriefingRoom.PrintToLog($"No Units found that exceed requested TargetCount", LogMessageErrorLevel.Error);
[nitpick] no need for this log

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +            throw new BriefingRoomException("Requested Target Count greater than Maximum Configured Target Count");
[suggesion] switch this round so its if error and default returns

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
[suggesion] with the added units I don't think we will need this logic to reduce the minimum. Just filter down to what is valid and throw an error if for some reason we have nothing.

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                                validUnitsDCSIDsLengths[country].Where(unit => unit.ID == unitID).First(),
[suggesion] just move this line into LimitValidUnitsByMinMax

2022-03-01 18:54 UTC, john681611 commented on Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
> +            // Set whether or not the Objective is Hidden.. options: Never OR Always
[nitpick] comment not needed here as code should be clear enough.

2022-03-01 19:03 UTC, NovaLogicDev commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                    validUnits = countMinMax.HasValue ? LimitValidUnitsByRequestedUnitCount(countMinMax.Value, validUnits): validUnits;
yeah, indeed. I'm kicking myself I missed this first go around.

2022-03-01 22:29 UTC, NovaLogicDev commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
```C#
                do
                {
                    if (countMinTemp < countMinMax.Max) BriefingRoom.PrintToLog("Minimum Target Count is lower than requested!", LogMessageErrorLevel.Warning);
                    validUnitsGroupSizeBetweenMinAndMax[country] ....
```
Something like this potentially?

2022-03-02 22:19 UTC, john681611 commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
Seems sensible. Advantage of open source software is people are free to mess with it but they can't blame you when they break it :D

2022-03-03 00:50 UTC, NovaLogicDev commented on Source/BriefingRoom/Data/Entries/DBEntryCoalition.cs
> +                while (!(validUnitsGroupSizeBetweenMinAndMax[country].Count > 0));
Agreed, I'll implement and send in the rest of the updates.

2022-03-04 08:49 UTC, john681611 approved these changes

2022-03-04 08:49 UTC, merged